# Generated by Django 3.2.7 on 2021-09-12 20:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(default='', max_length=256)),
                ('last_name', models.CharField(default='', max_length=256)),
                ('phone', models.CharField(default='', max_length=256)),
                ('email', models.EmailField(default='', max_length=254)),
            ],
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=256)),
                ('description', models.CharField(max_length=256)),
                ('status', models.CharField(choices=[('TODO', 'todo'), ('DONE', 'done')], default='TODO', max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=256)),
                ('beginning_date', models.DateField(blank=True)),
                ('end_date', models.DateField(blank=True)),
                ('employee_list', models.ManyToManyField(blank=True, help_text='employees on a project', related_name='employee_of', to='app.Employee')),
                ('task_list', models.ForeignKey(blank=True, help_text='tasks of a project', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tasks_of', to='app.task')),
            ],
        ),
        migrations.AddField(
            model_name='employee',
            name='task_list',
            field=models.ForeignKey(blank=True, help_text='employee on a task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_of', to='app.task'),
        ),
    ]
