# Generated by Django 3.2.7 on 2021-09-12 20:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='task_list',
        ),
        migrations.AddField(
            model_name='task',
            name='employee_list',
            field=models.ForeignKey(blank=True, help_text='employee on a task', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='task_of', to='app.employee'),
        ),
    ]
