# Generated by Django 3.2.7 on 2021-09-12 20:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20210912_2050'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='employee_list',
            new_name='employee',
        ),
    ]
