# Generated by Django 3.0.14 on 2021-09-13 05:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_rename_employee_list_task_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='task_list',
        ),
        migrations.AddField(
            model_name='task',
            name='project',
            field=models.ForeignKey(blank=True, help_text='project bound to a task', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='task_of', to='app.Task'),
        ),
    ]
