# Generated by Django 3.0.14 on 2021-09-13 06:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20210913_0557'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='employee_list',
            field=models.ManyToManyField(blank=True, help_text='employees on a project', related_name='project_of', to='app.Employee'),
        ),
    ]
